// GENERATED by `drizzle-kit pull` — Drizzle relations for the site schema.
// See ./schema.ts for provenance and how to regenerate.

import { relations } from "drizzle-orm/relations";
import { profiles, talks, talkContent, blogPosts, connections, meetups, events, applications, blockedUsers, broadcastAccounts, broadcastChannels, projects, communityContacts, contentEvents, conversations, feedback, comments, hackathonSubmissions, hackathonScores, homeVisions, identities, matcherContacts, matcherEvents, messages, mulerunDemos, mulerunVotes, podcasts, podcastGuests, profileEventNotes, reports, scheduledPosts, socialConnections, valuePortfolio, likes } from "./schema";

export const talksRelations = relations(talks, ({one, many}) => ({
	profiles: one(profiles, {
		fields: [talks.createdBy],
		references: [profiles.id]
	}),
	talkContents: many(talkContent),
}));

export const profilesRelations = relations(profiles, ({many}) => ({
	talkss: many(talks),
	blogPostss: many(blogPosts),
	connectionss_recipientId: many(connections, {
		relationName: "connections_recipientId_profiles_id"
	}),
	connectionss_requesterId: many(connections, {
		relationName: "connections_requesterId_profiles_id"
	}),
	meetupss: many(meetups),
	eventss: many(events),
	applicationss: many(applications),
	blockedUserss_blockedId: many(blockedUsers, {
		relationName: "blockedUsers_blockedId_profiles_id"
	}),
	blockedUserss_blockerId: many(blockedUsers, {
		relationName: "blockedUsers_blockerId_profiles_id"
	}),
	broadcastAccountss: many(broadcastAccounts),
	broadcastChannelss: many(broadcastChannels),
	projectss: many(projects),
	communityContactss: many(communityContacts),
	contentEventss: many(contentEvents),
	conversationss_participant1: many(conversations, {
		relationName: "conversations_participant1_profiles_id"
	}),
	conversationss_participant2: many(conversations, {
		relationName: "conversations_participant2_profiles_id"
	}),
	feedbacks: many(feedback),
	commentss: many(comments),
	homeVisionss: many(homeVisions),
	identitiess: many(identities),
	matcherContactss: many(matcherContacts),
	matcherEventss: many(matcherEvents),
	messagess: many(messages),
	podcastss: many(podcasts),
	podcastGuestss: many(podcastGuests),
	profileEventNotess_createdBy: many(profileEventNotes, {
		relationName: "profileEventNotes_createdBy_profiles_id"
	}),
	profileEventNotess_profileId: many(profileEventNotes, {
		relationName: "profileEventNotes_profileId_profiles_id"
	}),
	reportss_reportedUserId: many(reports, {
		relationName: "reports_reportedUserId_profiles_id"
	}),
	reportss_reporterId: many(reports, {
		relationName: "reports_reporterId_profiles_id"
	}),
	scheduledPostss: many(scheduledPosts),
	socialConnectionss: many(socialConnections),
	valuePortfolios: many(valuePortfolio),
	likess: many(likes),
}));

export const talkContentRelations = relations(talkContent, ({one}) => ({
	talks: one(talks, {
		fields: [talkContent.talkId],
		references: [talks.id]
	}),
}));

export const blogPostsRelations = relations(blogPosts, ({one}) => ({
	profiles: one(profiles, {
		fields: [blogPosts.authorId],
		references: [profiles.id]
	}),
}));

export const connectionsRelations = relations(connections, ({one}) => ({
	profiles_recipientId: one(profiles, {
		fields: [connections.recipientId],
		references: [profiles.id],
		relationName: "connections_recipientId_profiles_id"
	}),
	profiles_requesterId: one(profiles, {
		fields: [connections.requesterId],
		references: [profiles.id],
		relationName: "connections_requesterId_profiles_id"
	}),
}));

export const meetupsRelations = relations(meetups, ({one, many}) => ({
	profiles: one(profiles, {
		fields: [meetups.createdBy],
		references: [profiles.id]
	}),
	profileEventNotess: many(profileEventNotes),
}));

export const eventsRelations = relations(events, ({one}) => ({
	profiles: one(profiles, {
		fields: [events.createdBy],
		references: [profiles.id]
	}),
}));

export const applicationsRelations = relations(applications, ({one}) => ({
	profiles: one(profiles, {
		fields: [applications.reviewedBy],
		references: [profiles.id]
	}),
}));

export const blockedUsersRelations = relations(blockedUsers, ({one}) => ({
	profiles_blockedId: one(profiles, {
		fields: [blockedUsers.blockedId],
		references: [profiles.id],
		relationName: "blockedUsers_blockedId_profiles_id"
	}),
	profiles_blockerId: one(profiles, {
		fields: [blockedUsers.blockerId],
		references: [profiles.id],
		relationName: "blockedUsers_blockerId_profiles_id"
	}),
}));

export const broadcastAccountsRelations = relations(broadcastAccounts, ({one}) => ({
	profiles: one(profiles, {
		fields: [broadcastAccounts.userId],
		references: [profiles.id]
	}),
}));

export const broadcastChannelsRelations = relations(broadcastChannels, ({one}) => ({
	profiles: one(profiles, {
		fields: [broadcastChannels.userId],
		references: [profiles.id]
	}),
}));

export const projectsRelations = relations(projects, ({one, many}) => ({
	profiles: one(profiles, {
		fields: [projects.userId],
		references: [profiles.id]
	}),
	commentss: many(comments),
	reportss: many(reports),
	likess: many(likes),
}));

export const communityContactsRelations = relations(communityContacts, ({one}) => ({
	profiles: one(profiles, {
		fields: [communityContacts.matchedProfileId],
		references: [profiles.id]
	}),
}));

export const contentEventsRelations = relations(contentEvents, ({one}) => ({
	profiles: one(profiles, {
		fields: [contentEvents.userId],
		references: [profiles.id]
	}),
}));

export const conversationsRelations = relations(conversations, ({one, many}) => ({
	profiles_participant1: one(profiles, {
		fields: [conversations.participant1],
		references: [profiles.id],
		relationName: "conversations_participant1_profiles_id"
	}),
	profiles_participant2: one(profiles, {
		fields: [conversations.participant2],
		references: [profiles.id],
		relationName: "conversations_participant2_profiles_id"
	}),
	messagess: many(messages),
}));

export const feedbackRelations = relations(feedback, ({one}) => ({
	profiles: one(profiles, {
		fields: [feedback.userId],
		references: [profiles.id]
	}),
}));

export const commentsRelations = relations(comments, ({one, many}) => ({
	projects: one(projects, {
		fields: [comments.projectId],
		references: [projects.id]
	}),
	profiles: one(profiles, {
		fields: [comments.userId],
		references: [profiles.id]
	}),
	reportss: many(reports),
}));

export const hackathonScoresRelations = relations(hackathonScores, ({one}) => ({
	hackathonSubmissions: one(hackathonSubmissions, {
		fields: [hackathonScores.submissionId],
		references: [hackathonSubmissions.id]
	}),
}));

export const hackathonSubmissionsRelations = relations(hackathonSubmissions, ({many}) => ({
	hackathonScoress: many(hackathonScores),
}));

export const homeVisionsRelations = relations(homeVisions, ({one}) => ({
	profiles: one(profiles, {
		fields: [homeVisions.userId],
		references: [profiles.id]
	}),
}));

export const identitiesRelations = relations(identities, ({one}) => ({
	profiles: one(profiles, {
		fields: [identities.userId],
		references: [profiles.id]
	}),
}));

export const matcherContactsRelations = relations(matcherContacts, ({one}) => ({
	profiles: one(profiles, {
		fields: [matcherContacts.userId],
		references: [profiles.id]
	}),
}));

export const matcherEventsRelations = relations(matcherEvents, ({one}) => ({
	profiles: one(profiles, {
		fields: [matcherEvents.userId],
		references: [profiles.id]
	}),
}));

export const messagesRelations = relations(messages, ({one}) => ({
	conversations: one(conversations, {
		fields: [messages.conversationId],
		references: [conversations.id]
	}),
	profiles: one(profiles, {
		fields: [messages.senderId],
		references: [profiles.id]
	}),
}));

export const mulerunVotesRelations = relations(mulerunVotes, ({one}) => ({
	mulerunDemos_firstId: one(mulerunDemos, {
		fields: [mulerunVotes.firstId],
		references: [mulerunDemos.id],
		relationName: "mulerunVotes_firstId_mulerunDemos_id"
	}),
	mulerunDemos_secondId: one(mulerunDemos, {
		fields: [mulerunVotes.secondId],
		references: [mulerunDemos.id],
		relationName: "mulerunVotes_secondId_mulerunDemos_id"
	}),
	mulerunDemos_thirdId: one(mulerunDemos, {
		fields: [mulerunVotes.thirdId],
		references: [mulerunDemos.id],
		relationName: "mulerunVotes_thirdId_mulerunDemos_id"
	}),
}));

export const mulerunDemosRelations = relations(mulerunDemos, ({many}) => ({
	mulerunVotess_firstId: many(mulerunVotes, {
		relationName: "mulerunVotes_firstId_mulerunDemos_id"
	}),
	mulerunVotess_secondId: many(mulerunVotes, {
		relationName: "mulerunVotes_secondId_mulerunDemos_id"
	}),
	mulerunVotess_thirdId: many(mulerunVotes, {
		relationName: "mulerunVotes_thirdId_mulerunDemos_id"
	}),
}));

export const podcastsRelations = relations(podcasts, ({one, many}) => ({
	profiles: one(profiles, {
		fields: [podcasts.createdBy],
		references: [profiles.id]
	}),
	podcastGuestss: many(podcastGuests),
}));

export const podcastGuestsRelations = relations(podcastGuests, ({one}) => ({
	podcasts: one(podcasts, {
		fields: [podcastGuests.podcastId],
		references: [podcasts.id]
	}),
	profiles: one(profiles, {
		fields: [podcastGuests.profileId],
		references: [profiles.id]
	}),
}));

export const profileEventNotesRelations = relations(profileEventNotes, ({one}) => ({
	profiles_createdBy: one(profiles, {
		fields: [profileEventNotes.createdBy],
		references: [profiles.id],
		relationName: "profileEventNotes_createdBy_profiles_id"
	}),
	meetups: one(meetups, {
		fields: [profileEventNotes.meetupId],
		references: [meetups.id]
	}),
	profiles_profileId: one(profiles, {
		fields: [profileEventNotes.profileId],
		references: [profiles.id],
		relationName: "profileEventNotes_profileId_profiles_id"
	}),
}));

export const reportsRelations = relations(reports, ({one}) => ({
	comments: one(comments, {
		fields: [reports.commentId],
		references: [comments.id]
	}),
	projects: one(projects, {
		fields: [reports.projectId],
		references: [projects.id]
	}),
	profiles_reportedUserId: one(profiles, {
		fields: [reports.reportedUserId],
		references: [profiles.id],
		relationName: "reports_reportedUserId_profiles_id"
	}),
	profiles_reporterId: one(profiles, {
		fields: [reports.reporterId],
		references: [profiles.id],
		relationName: "reports_reporterId_profiles_id"
	}),
}));

export const scheduledPostsRelations = relations(scheduledPosts, ({one}) => ({
	profiles: one(profiles, {
		fields: [scheduledPosts.userId],
		references: [profiles.id]
	}),
}));

export const socialConnectionsRelations = relations(socialConnections, ({one}) => ({
	profiles: one(profiles, {
		fields: [socialConnections.userId],
		references: [profiles.id]
	}),
}));

export const valuePortfolioRelations = relations(valuePortfolio, ({one}) => ({
	profiles: one(profiles, {
		fields: [valuePortfolio.userId],
		references: [profiles.id]
	}),
}));

export const likesRelations = relations(likes, ({one}) => ({
	projects: one(projects, {
		fields: [likes.projectId],
		references: [projects.id]
	}),
	profiles: one(profiles, {
		fields: [likes.userId],
		references: [profiles.id]
	}),
}));